In [1]:
import pandas as pd
data = {
    'town': [
        'monroe township', 'monroe township', 'monroe township', 'monroe township', 'monroe township',
        'west windsor', 'west windsor', 'west windsor', 'west windsor',
        'robinsville', 'robinsville', 'robinsville', 'robinsville'
    ],
    'area': [
        2600, 3000, 3200, 3600, 4000,
        2600, 2800, 3300, 3600,
        2600, 2900, 3100, 3600
    ],
    'price': [
        550000, 565000, 610000, 680000, 725000,
        585000, 615000, 650000, 710000,
        575000, 600000, 620000, 695000
    ]
}
df = pd.DataFrame(data)
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [23]:


#1st METHOD 
#through pandas get_dummies

In [24]:
dummies = pd.get_dummies(df.town,dtype=int)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [25]:
merged = pd.concat([df,dummies],axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [26]:
#the reason of dropping 'town' is cuz , as we already have dummy variables columns so we can do the calc throught that 
#no need of extra column
#Reason of dropping one of this dummy variable column , i need to google this .But it has said that if you have 5 dummy columns then drop 
#one column ,,because ofmulticollinearity 
#DUMMY VARIABLE TRAP se bachne ke liye we drop smth like that !!

final = merged.drop(['town','west windsor'],axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [27]:
#X is having independent variable
X= final.drop('price',axis='columns')
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [28]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [29]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [30]:
model.fit(X,y)

LinearRegression()

In [31]:
#town:-robbinsville
model.predict([[2800,0,1]])

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [32]:
#twon:- wind 
model.predict([[2800,0,0]])

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([605103.20361213])

In [33]:
#town:- monroe
model.predict([[2800,1,0]])

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([565089.22812299])

In [22]:


#2nd METHOD !!!!!
#THROUGH SKLEARN ONE HOT ENCODER

In [34]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [46]:
#In order to ONE HOT ENCODING first you need to do labelencoding to that text independent column !

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [45]:
#fit_transform takes the label column as an argument/input and return the labels 
#in this case , it is 0,2,1

dfle = df
le.fit_transform(dfle.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [47]:
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [51]:
#now the same process take X and y 
#the reason of taking X as values because we dont need X to return as a dataframe , instead we need it as a 2D array
X= dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [52]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [74]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

#creating an object so that baar baar itna bda naam na likhna pde

ohe = OneHotEncoder()


# apply OneHotEncoder to column index 0
column_transformer = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])
    ],
    remainder='passthrough'  # leave other columns as is
)

# Fit and transform your data
X = column_transformer.fit_transform(X)

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [58]:
#the reason of using columnTransformer is because if in the nxt step if i put X as an input ohe.fit_transform()
#then it will consider all the columns as label which is eventually wrong 
# through this , we make sure ki joh label column h sirf whi consider ho which is in this case is 'town' the 0th column
#remainder ='passthrough' means the rest of the column shud not get affected through this columnTransformer

In [64]:
X = X[:,1:] #takes all rows and drops oth column and considering columns starting from 1
X

array([[1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [65]:
#Now the same step
model.fit(X,y)

LinearRegression()

In [66]:
model.predict([[1,0,2800]])

ValueError: X has 3 features, but LinearRegression is expecting 13 features as input.